### ISSUE TITLE
Create database docker on tests startup

### ISSUE THREAD

**Issue by Prytu** [VirrageS/chirp#122]
At the moment I use test database that is created together with other services and runs all the time. Change it so that database is started on test startup and closed after test are finished.

Useful links:
https://divan.github.io/posts/integration_testing/

**Comment by VirrageS** [comment]
We still want to do this :C ?

**Comment by Prytu** [comment]
This is a thing to discuss, I would like to have this. But if you don't want to, we can skip it

**Comment by VirrageS** [comment]
I opt for skipping it and add it later. I would make Makefile and add make test function which would make docker compose up test then run tests and make docker compose down

**Comment by Prytu** [comment]
This will be fixed by #148
