### ISSUE TITLE
Discuss the final architecture of our backend

### ISSUE THREAD

**Issue by Prytu** [VirrageS/chirp#123]
Discuss:
- [x] Database architecture
- [x] Cache
- [x] Full text search
- [ ] Load balancer

**Comment by Prytu** [comment]
idea 1:
- use SQL (postgres) database as the only database
- use Redis as NoSQL cache
- maybe some full text search for tweets etc? (elasticsearch?)
- probably varnish as loadbalancer

**Comment by VirrageS** [comment]
- we will use just MySQL as main and only database.
- Redis will be mainly used as cache and maybe as NoSQL database.
- for full-text search will use Sphinx.
- Varnish will be used if we will have time for that.

**Comment by Prytu** [comment]
https://developers.google.com/speed/pagespeed/module/config_filters and maybe this :)

**Comment by VirrageS** [comment]
I will consider this but in frontend I use webpack which compress and optimize a lot of files. Moreover I am not sure if we will use nginx because now it doesnt work. I will try to fix it but I am not sure if I succeed

**Comment by Prytu** [comment]
Yeah, sure. Just posting a link in case we want to use it
