### ISSUE TITLE
Cache should be cleaned after delete or insert

### ISSUE THREAD

**Issue by VirrageS** [VirrageS/chirp#164]
If cache is not cleaned upon insertion of tweet or user this can lead to some weird frontend bugs which we would like to avoid.

Another approach (which can be very time consuming) would be informing some service that insertion has occurred and fire recaching which would result in fetching all possible changed queries from database and put results in cache.

**Comment by Prytu** [comment]
fixed by #170

**Comment by VirrageS** [comment]
This is still issue is still valid when inserting tweet.
