### ISSUE TITLE
`null` response when returning 0 sized array

### ISSUE THREAD

**Issue by VirrageS** [VirrageS/chirp#165]
When hitting `/home_feed` when user has not created any tweet it will result in `null` response instead of `[]` as expected. It is because in **json.Marshal** `empty array != nil slice`:
```
var tweets []*model.Tweet
assert(tweets == nil) // true
```

proper approach to this problem is to initialize variable:
```
tweets := []*model.Tweets{} // not sure about this but should work
```
or 
```
tweets := make([]*model.Tweets, 0)
```

And this problem is not just in `/home_feed`!

**Comment by VirrageS** [comment]
More informations: https://github.com/gin-gonic/gin/issues/125

**Comment by Prytu** [comment]
Im going to check this, because I remember fixing it earlier. Maybe I've lost it during refactoring.

**Comment by VirrageS** [comment]
This issue can be connected with my changes in cache.
