### ISSUE TITLE
Change the way we use cache

### ISSUE THREAD

**Issue by Prytu** [VirrageS/chirp#171]
At the moment for Users we add to cache a user object that is calculated for a given requesting user (i.e it has 'following' set). I think it should be better to store User without this info in cache and then fetch the 'following' database or another object in cache.
The same with tweets and 'liked' field.

What do you think?

**Comment by VirrageS** [comment]
Good idea but I think it can introduce some redundant structures (not sure how to avoid this).

Similar approach would be to cache every piece of information. So `name`, `username` etc. will be stored for a given user. It adds a lot of new keys to cache which can potentially make it slow (eg. when keys are not hashed but kept in some kind of order). Next drawback of this idea is that it adds a lot of requests to cache. We can do them in parallel but not sure if this wouldn't kill cache.
On the other hand this approach gives us flexibility and keeps a lot of not fast changing (but often requested) values what result in high cache hit rate.
