### ISSUE TITLE
Consider creating another set of models for database access

### ISSUE THREAD

**Issue by Prytu** [VirrageS/chirp#174]
At the moment our idea for collecting data from database is that we don't use SQL joins, but we fetch each type of data separately. What happens now is that our model for users in our service, storage and API is different from DB model (e.g Users have `following` and `follower_count` fields that are not a part of user table in DB. Therefore when we fetch data from database, we save it on a User (or PublicUser) model with default values for those fields. This is not a big problem when we remember that, but I think that this can be a cause for some stupid bugs etc. So I think that we should discuss and consider creating separate model for DB that would reflect DB tables and then add converters between models of DB and the rest of the system. This will definitely require some code duplication, but I think that its worth it, because this will make bug much easier to spot and generally make the code a bit easier to follow.

**Comment by VirrageS** [comment]
I get the problem but I think this is not required and only will involve some unnecessary code. During conversion you are also prone to stupid bugs, so the only remedy for that, in my opinion, are tests.
I would opt for abandoning this idea.
