### ISSUE TITLE
Search endpoint - 500 internal server error

### ISSUE THREAD

**Issue by VirrageS** [VirrageS/chirp#187]
When trying to perform GET request `/search?querystring=hello` I get this error:
```
[GIN] 2017/01/09 - 12:41:21 | 500 |   18.348643ms | 127.0.0.1 |   GET     /search
Error #01: Internal server error.
```

It is my fault or current implementation has some kind of bug?

**Comment by Prytu** [comment]
Is there any other debug message there other than `Error #01: Internal server error.`

**Comment by VirrageS** [comment]
Unfortunately not.
