### ISSUE TITLE
Unify class/interface/file names

### ISSUE THREAD

**Issue by Prytu** [VirrageS/chirp#222]
In some places of the code we have names like PasswordManager interface in password package and in others we've got <package_name>.Manager (or something like that). In most of the Go code I've seen they call it e.g. password.Manager (and I believe this kind of naming is recommended).

Also the filename of interfaces of a package is sometimes called `interface.go`, sometimes `interfaces.go` and sometimes the name is similar to the interface name. I think that we should discuss the naming and just stick to one style.

**Comment by VirrageS** [comment]
Hmm we can stick with `Manager.go` etc. naming, without adding `Password...`, `Token...` etc.

And when it comes to `interface` naming. I would name everything `providers.go` and actual interfaces name `SmthProvider`. Do you have any preferences?
