### ISSUE TITLE
Refactor routing

### ISSUE THREAD

**Issue by VirrageS** [VirrageS/chirp#60]
There is a problem with routing which in my opinion should be resolved.
There is no way to specify such routing:

- /users/:id
- /users/feed

Gin panics because it thinks that this two routes overlap.

It's pain in the ass when trying to make more complex routing. We should create some kind of middleware which would look into path and dispatch specific functions when there is a match.

**Comment by Prytu** [comment]
Do you think so? I thnik that feed could is a different resource than 'user'. If you mean the home feed we could just another endpoint: /home_feed or something like that where you would recieve a feed of the user that authenticates with the request. And if you want to get feed of a given user (Im not sure if Twitter supports such thing) I'd just do it at /usuer/:id/feed probably. What do you think?

**Comment by VirrageS** [comment]
This routes, will not work in my opinion:
 - /users/:id
 - /users/:id/feed

And what about tweets which belongs to specific user? We want that too. So we would would need another path:
 - /users/:id
 - /users/:id/feed
 - /users/:id/tweets

I thought that it is better to get make `/users/feed` endpoint since we will never want to get feed of user other than currently authenticated / logged in, so we do not need to specify `:id` of user.
