### ISSUE TITLE
Research on Dependency Injection frameworks in Go

### ISSUE THREAD

**Issue by Prytu** [VirrageS/chirp#82]
- [ ] Find out if using DI frameworks is 'idiomatic-Go'
- [ ] If yes, find the best DI framework for Go
- [ ] Implement DI using the framework

**Comment by VirrageS** [comment]
I think DI should be avoided in Go, even it is very desirable.

**Comment by Prytu** [comment]
Lets leave it for later. At the moment we dont need it.

**Comment by VirrageS** [comment]
Is this still valid issue?
