### ISSUE TITLE
Find out how to implement user's login for longer than expiration period on auth token

### ISSUE THREAD

**Issue by Prytu** [VirrageS/chirp#91]
At the moment the only way to obtain a valid token is by loggin in. The problem is that this way frontend will need to either:
a) store users password
b) make him login every <expiration_period> of auth token.
(b) is a terrible UX, so we need to find out if (a) is a good idea or find other way to implement it.
This would be solved by using refresh token or something like that. Let's find out how to implement it with JWT without storing anything in backed or if its impossible discuss another approach to auth tokens.

**Comment by Prytu** [comment]
https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/ useful link

**Comment by VirrageS** [comment]
This issue is connected to #63

**Comment by VirrageS** [comment]
Could you try to implement refresh tokens? It would help me a lot, to make some progress about this.
